/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica5;

/**
 *
 * @author alesa
 */
public class Practica5 extends javax.swing.JFrame {
    
    /**
     * Creates new form Practica5
     */
    public Practica5() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        try {
            lienzo1 = new com.mycompany.practica5.Lienzo();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        try {
            logo1 = new com.mycompany.practica5.Logo();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jPanel1 = new javax.swing.JPanel();
        SupIzq = new javax.swing.JRadioButton();
        SupDer = new javax.swing.JRadioButton();
        InfIzq = new javax.swing.JRadioButton();
        InfDer = new javax.swing.JRadioButton();
        Todos = new javax.swing.JCheckBox();
        Rojo = new javax.swing.JCheckBox();
        Verde = new javax.swing.JCheckBox();
        Azul = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lienzo1.setBackground(new java.awt.Color(255, 255, 255));

        logo1.setBackground(new java.awt.Color(255, 255, 255));
        logo1.setLayout(new javax.swing.OverlayLayout(logo1));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lienzo1Layout.createSequentialGroup()
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lienzo1Layout.createSequentialGroup()
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(SupIzq);
        SupIzq.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        SupIzq.setForeground(new java.awt.Color(204, 0, 0));
        SupIzq.setText("Superior izquierda");
        SupIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupIzqActionPerformed(evt);
            }
        });

        buttonGroup1.add(SupDer);
        SupDer.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        SupDer.setForeground(new java.awt.Color(204, 0, 0));
        SupDer.setText("Superior derecha");
        SupDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupDerActionPerformed(evt);
            }
        });

        buttonGroup1.add(InfIzq);
        InfIzq.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        InfIzq.setForeground(new java.awt.Color(204, 0, 0));
        InfIzq.setText("Inferior izquierda");
        InfIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfIzqActionPerformed(evt);
            }
        });

        buttonGroup1.add(InfDer);
        InfDer.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        InfDer.setForeground(new java.awt.Color(204, 0, 0));
        InfDer.setSelected(false);
        InfDer.setText("Inferior derecha");
        InfDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfDerActionPerformed(evt);
            }
        });

        Todos.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Todos.setForeground(new java.awt.Color(238, 158, 7));
        Todos.setText("Todos");
        Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosActionPerformed(evt);
            }
        });

        Rojo.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Rojo.setForeground(new java.awt.Color(238, 158, 7));
        Rojo.setText("Rojo");
        Rojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RojoStateChanged(evt);
            }
        });
        Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RojoActionPerformed(evt);
            }
        });

        Verde.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Verde.setForeground(new java.awt.Color(238, 158, 7));
        Verde.setText("Verde");
        Verde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                VerdeStateChanged(evt);
            }
        });
        Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeActionPerformed(evt);
            }
        });

        Azul.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        Azul.setForeground(new java.awt.Color(238, 158, 7));
        Azul.setText("Azul");
        Azul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AzulStateChanged(evt);
            }
        });
        Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Paleta de colores");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Posicion de logo");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alejandro Santana Amador, Daniel Naranjo Torres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Todos)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rojo)
                            .addComponent(Azul)
                            .addComponent(Verde)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SupIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SupDer))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(InfIzq)
                            .addGap(18, 18, 18)
                            .addComponent(InfDer))))
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(Rojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Verde)
                            .addComponent(Todos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Azul))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupIzq)
                            .addComponent(SupDer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InfIzq)
                            .addComponent(InfDer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        SupDer.setSelected(true);
        Rojo.setSelected(true);
        Azul.setSelected(true);
        Verde.setSelected(true);
        Todos.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lienzo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosActionPerformed
        // TODO add your handling code here:
        
        Todos.setSelected(true);
        Rojo.setSelected(true);Azul.setSelected(true);Verde.setSelected(true);
        actualizeColors();    
    }//GEN-LAST:event_TodosActionPerformed

    private void RojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RojoStateChanged
       
    }//GEN-LAST:event_RojoStateChanged

    private void VerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_VerdeStateChanged
        
    }//GEN-LAST:event_VerdeStateChanged

    private void AzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AzulStateChanged
        
    }//GEN-LAST:event_AzulStateChanged

    private void RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RojoActionPerformed
        
        if(!Azul.isSelected() && !Verde.isSelected()) Rojo.setSelected(true);
        areAllSelected();
        actualizeColors();
    }//GEN-LAST:event_RojoActionPerformed

    private void VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeActionPerformed
        
        if(!Azul.isSelected() && !Rojo.isSelected()) Verde.setSelected(true);
        areAllSelected();
        actualizeColors();
    }//GEN-LAST:event_VerdeActionPerformed

    private void AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulActionPerformed
        
        if(!Rojo.isSelected() && !Verde.isSelected()) Azul.setSelected(true);
        areAllSelected();
        actualizeColors();
    }//GEN-LAST:event_AzulActionPerformed

    private void SupIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupIzqActionPerformed
        // TODO add your handling code here:
        logo1.setPosition(0, 20);
        logo1.repaint();
    }//GEN-LAST:event_SupIzqActionPerformed

    private void SupDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupDerActionPerformed
        // TODO add your handling code here:
        logo1.setPosition(lienzo1.getX()+lienzo1.getWidth()-320, 20);
        logo1.repaint();               
    }//GEN-LAST:event_SupDerActionPerformed

    private void InfIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfIzqActionPerformed
        // TODO add your handling code here:
        logo1.setPosition(0, lienzo1.getHeight()-150);
        logo1.repaint();
    }//GEN-LAST:event_InfIzqActionPerformed

    private void InfDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfDerActionPerformed
        // TODO add your handling code here:
        logo1.setPosition(lienzo1.getX()+lienzo1.getWidth()-320, lienzo1.getHeight()-150);
        logo1.repaint();
    }//GEN-LAST:event_InfDerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica5().setVisible(true);
            }
        });
    }

    public void actualizeColors(){
        this.lienzo1.setImg(UtilsPractica5.seleccionarComponentes(lienzo1.getImg(), Rojo.isSelected(), Verde.isSelected(), Azul.isSelected()));
        repaint();
    }
    public void areAllSelected(){
        if(Rojo.isSelected() && Verde.isSelected() && Azul.isSelected()){
            Todos.setSelected(true);
        }else{
            Todos.setSelected(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Azul;
    private javax.swing.JRadioButton InfDer;
    private javax.swing.JRadioButton InfIzq;
    private javax.swing.JCheckBox Rojo;
    private javax.swing.JRadioButton SupDer;
    private javax.swing.JRadioButton SupIzq;
    private javax.swing.JCheckBox Todos;
    private javax.swing.JCheckBox Verde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.mycompany.practica5.Lienzo lienzo1;
    private com.mycompany.practica5.Logo logo1;
    // End of variables declaration//GEN-END:variables
}
